# railway.toml
[build]
builder           = "DOCKERFILE"
dockerfilePath    = "./Dockerfile"
dockerBuildTarget = "runtime"

[deploy]
startCommand            = "python migrations/migrate.py && python -u bot.py"
restartPolicyType       = "ON_FAILURE"
restartPolicyMaxRetries = 10


